title: Manual of Me
description: A personal guide on how I work, communicate, and collaborate.
theme: jekyll-theme-cayman
search_enabled: true
show_downloads: false
github:
  is_project_page: false
url: "https://jrabbott.github.io/manual-of-me"
